import VersoBlog
import Blog.Categories
import Blog.Meta
open Verso Genre Blog

#doc (Post) "HEq and Axiom K: An Exploration in Lean" =>

%%%
authors := ["berberman"]
date := {year := 2026, month := 2, day := 23}
categories := [Category.lean]
%%%

```leanInit empty
```


While reading Conor McBride's _A Few Constructions on Constructors_,
I came across his definition of Heterogeneous Equality (represented here using Lean axioms):

```lean empty

-- Type constructor
axiom HEq' : {α : Sort u} → α → {β : Sort u} → β → Prop

-- Data constructor
axiom HEq'.refl {α : Sort u} (a : α) : HEq' a a

-- Eliminator
axiom HEq'.rec {α : Sort u} {a : α}
  {motive : {β : Sort u} → (b : β) → HEq' a b → Sort v}
  (refl : motive a (HEq'.refl a))
  {β : Sort u} {b : β} (h : HEq' a b) :
  motive b h

```

He also introduced a special elimination rule:

```lean empty
axiom HEq'.rec' {α : Sort u} {a : α}
  {motive : (b : α) → HEq' a b → Sort v}
  (refl : motive a (HEq'.refl a)) {b : α} (h : HEq' a b) :
  motive b h
```

Notice how this special recursor differs from the standard one: its motive fixes the type of the second index, `b`, to `α`.
The author then mentions that heterogeneous equality (equipped with this special eliminator) is as strong as homogeneous equality plus Axiom K.
The construction involves representing heterogeneous equality as homogeneous equality over sigma types.
In this way, `(Σ α, x : α) = (Σ α, y : α) → x = y` is equivalent to K.

I was quite confused when I first read this. I realized I had never truly understood how equality recursors or Axioms J and K worked, nor how heterogeneous equality related to them.
Therefore, I figured it would be an excellent exercise to manually derive in Lean how this special eliminator, combined with HEq, implies K.
With my advisor's help, we completed this exercise, and this post summarizes our proofs.

> Since Lean inherently supports Uniqueness of Identity Proofs (UIP), we must be extremely careful not to use it accidentally.
  This means we cannot use the cases tactic, nor can we use Lean's built-in `Eq` (`=`).
  Every operation must be implemented manually by invoking the `rec` function generated by our custom inductive type.

We start by defining a homogeneous equality with a universe level of at least `Type`:

```lean empty
inductive Eq' {α : Sort u} : α → α → Sort (max u 1) where
  | refl (x : α) : Eq' x x

infix:50 " ≡ " => Eq'

def Eq'.rfl {α : Sort u} {x : α} : x ≡ x := refl x

noncomputable def Eq'.subst {α : Sort u}
  {motive : α → Sort v} {x y : α}
  (h₁ : x ≡ y) (h₂ : motive x) : motive y := Eq'.rec h₂ h₁

noncomputable def Eq'.symm {α : Sort u} {x y : α} (h : x ≡ y) : y ≡ x :=
  Eq'.subst (motive := fun z => z ≡ x) h rfl
```

We use the `≡` symbol to denote our custom homogeneous equality. For convenience, we also define `subst` and `symm`.

For heterogeneous equality, we will directly use Lean's built-in `HEq` (`≍`).
As long as we avoid functions like `eq_of_heq` and refrain from using `cases` for dependent pattern matching, we are safe.
Let's add the special eliminator mentioned earlier:

```lean empty
axiom HEq.rec' {α : Sort u} {x : α} {motive : (y : α) → x ≍ y → Sort v}
      (refl : motive x (HEq.refl x)) {y : α} (h : x ≍ y) : motive y h
```

Our ultimate goal is to prove K, or its equivalent, UIP:

```lean empty
def eq_uip_sorry {α : Sort u} (x : α) (z : x ≡ x) : z ≡ (Eq'.refl x) := sorry
```

As mentioned earlier, unlike Agda, K cannot be disabled in Lean.
We must avoid using `cases` because it can immediately close this goal
(we will discuss what it actually does under the hood later, but for now, it's enough to know that it relies on UIP):

```lean empty
noncomputable def eq_uip' {α : Sort u} (x : α) (z : x ≡ x) : z ≡ (Eq'.refl x) := by
  cases z
  exact Eq'.rfl
```

Let's clarify our approach first. It is currently unclear how to obtain `z ≡ (Eq'.refl x)`.
We need a way to establish a connection with HEq because we must utilize that special eliminator.
We can start with the sigma type mentioned in the initial claim.
As discussed in [_On Heterogeneous Equality_](https://homotopytypetheory.org/2012/11/21/on-heterogeneous-equality/),
a sigma type is a pointed type, and heterogeneous equality is equivalent to homogeneous equality on pointed types.
We can prove this using the universe-polymorphic `PSigma` (denoted here with the notation `Σ'`):

These notations are equivalent:

```lean empty (name := sig1)
#check (α : Sort _) ×' α
```
```lean empty (name := sig2)
#check Σ' α : Sort _, α
```
```lean empty (name := sig3)
#check @PSigma (Sort _) (fun (α : Sort _) => α)
```
```leanOutput sig1
(α : Sort u_1) ×' α : Type u_1
```
```leanOutput sig2
(α : Sort u_1) ×' α : Type u_1
```
```leanOutput sig3
(α : Sort u_1) ×' α : Type u_1
```

```lean empty
def sigma_of_heq {α : Sort u} {x : α}
    {β : Sort u} (y : β)
    (h : x ≍ y) : (⟨α, x⟩ : Σ' α : Sort u, α) ≡ (⟨β, y⟩ : Σ' β : Sort u, β) :=
  HEq.rec
    (motive := fun {γ} y' _ => @Eq' (Σ' α : Sort u, α) ⟨α, x⟩ ⟨γ, y'⟩)
    Eq'.rfl
    h

def heq_of_sigma {α : Sort u} {x : α}
    {β : Sort u} (y : β)
    (h : (⟨α, x⟩ : Σ' α : Sort u, α) ≡ (⟨β, y⟩ : Σ' β : Sort u, β)) : x ≍ y :=
  let S : Σ' α : Sort u, α := ⟨α, x⟩
  let T : Σ' β : Sort u, β := ⟨β, y⟩
  have heq : S.2 ≍ T.2 := Eq'.subst (motive := fun S' => S.2 ≍ S'.2) h HEq.rfl
  heq
```

Without using `HEq.rec'` at all, we have achieved a bidirectional conversion between heterogeneous equality and homogeneous equality on sigma types.
Consider our goal `z ≡ (Eq'.refl x)`: its heterogeneous version `z ≍ Eq'.refl x` can be obtained by applying `heq_of_sigma` to ⟨`x ≡ x, z⟩ ≡ ⟨x ≡ x, Eq'.refl x⟩`.
And the `Eq'` of this sigma type can be proven directly:

```lean empty
noncomputable def sigma_eq {α : Sort u} (x : α) (z : x ≡ x) :
  (⟨x ≡ x, z⟩ : Σ' α : Sort (max 1 u), α) ≡ (⟨x ≡ x, Eq'.refl x⟩ : Σ' β : Sort (max 1 u), β) :=
  Eq'.rec
    (motive := fun x' q =>
      @Eq' (Σ' α : Sort (max 1 u), α) ⟨x ≡ x', q⟩ ⟨x ≡ x, Eq'.refl x⟩)
    Eq'.rfl
    z
```

So far, we have established the following path:

```
(z : x ≡ x)
------------- (sigma_eq)
⟨x ≡ x, z⟩ ≡ ⟨x ≡ x, Eq'.refl x⟩
------------- (heq_of_sigma)
z ≍ (Eq'.refl x)
------------- (???)
z ≡ (Eq'.refl x)
```

We are only one step away! Obviously, the missing link can be filled by `eq_of_heq`, but we are strictly restricted to using recursors.

```lean empty +error
noncomputable def HEq.eq'' {α : Sort u} (x y : α) (h : x ≍ y) : x ≡ y :=
  HEq.rec (motive := fun x' heq => x ≡ x') Eq'.rfl h
```

Unfortunately, the obvious elimination fails.
The second index `x'` has type `β`, and `heq : x ≍ x'` cannot cast the type of `x'` to match `x`.
Ah, finally, it's time to use that special eliminator for `HEq`:

```lean empty
noncomputable def HEq.eq' {α : Sort u} (x y : α) (h : x ≍ y) : x ≡ y :=
  HEq.rec' (motive := fun x' _ => x ≡ x') Eq'.rfl h
```

The motive forces the second index to have the same type as the first index, allowing us to successfully eliminate from `HEq` to `Eq`.
Now we can complete the proof:

```lean empty
noncomputable def eq_uip {α : Sort u} (x : α) (z : x ≡ x) : z ≡ (Eq'.refl x) := by
  apply HEq.eq'
  apply heq_of_sigma
  apply sigma_eq
```

With UIP at our disposal, proving K is a breeze:

```lean empty
noncomputable def K {α : Sort u} (x : α)
  {motive : x ≡ x → Sort v}
  (d : motive (Eq'.refl x))
  (z : x ≡ x) :
  motive z := Eq'.subst (Eq'.symm <| eq_uip x z) d
```

Conversely, K can also be used to prove UIP, as they are equivalent:

```lean empty
noncomputable example {α : Sort u} {x : α} (h : x ≡ x) : h ≡ Eq'.rfl :=
  K (motive := fun z => z ≡ Eq'.rfl) x Eq'.rfl h
```

In conclusion, the sole contribution of this axiom is essentially `eq_of_heq` (known as `JMeq_eq` in Coq),
which has been shown to imply Axiom K.
I believe these types and UIP-related concepts have fascinating interpretations in Homotopy Type Theory (HoTT),
but I unfortunately have zero background in HoTT...

Returning to the tactic-based proof, let's look at what Lean automatically did for us:

```lean empty (name := eq_uip')
#print eq_uip'
```

```leanOutput eq_uip' (whitespace := lax)
def eq_uip'.{u} : {α : Sort u} → (x : α) → (z : x ≡ x) → z ≡ Eq'.refl x :=
  fun {α} x z => Eq'.casesOn
   (motive := fun a t => x = a → z ≍ t → z ≡ Eq'.refl x) z
   (fun h h_1 => ⋯ ▸ Eq'.rfl) ⋯ ⋯
```

It generated some extra proof terms. Simplified and cleaned up, we get:

```lean empty
noncomputable def eq_uip'' {α : Sort u} (x : α) (z : x ≡ x) : z ≡ (Eq'.refl x) :=
  Eq'.rec
    (motive := fun y h => x = y → z ≍ h → z ≡ Eq'.refl x)
    (fun _ heq => Eq.rec (motive := fun y _ => z ≡ y) (Eq'.refl z) (eq_of_heq heq))
    z
    rfl
    HEq.rfl
```

It appears Lean inserted an `Eq` proof reliant on UIP within the motive's parameters,
but it doesn't play a crucial role. We can simplify it further:

```lean empty
noncomputable def eq_uip''' {α : Sort u} (x : α) (z : x ≡ x) : z ≡ (Eq'.refl x) :=
  Eq'.rec
    (motive := fun _ h => z ≍ h → z ≡ Eq'.refl x)
    (fun heq => Eq.rec (motive := fun y _ => z ≡ y) (Eq'.refl z) (eq_of_heq heq))
    z
    HEq.rfl
```
As we can see, the core of the proof uses `eq_of_heq` to convert `HEq` to `Eq`, and then eliminates it using `Eq.rec`.
This strictly relies on UIP.
